"""
Temperature Average Calculator Module

This module provides functionality to calculate the average of two temperature values.
It includes robust error handling for non-numeric inputs and a main execution block
with hard-coded sample values as required by the specification constraints (no user input).
"""

def get_temperature_input(prompt_message: str) -> float | None:
    """
    Attempts to retrieve a valid numeric temperature value from an external source.

    Since this script must run without interactive prompts, command-line arguments, or 
    network access per requirements, the actual conversion logic is prepared here but 
    not executed via input(). In a real-world scenario with user interaction, this function 
    would parse the string returned by input() and convert it to float.

    Args:
        prompt_message (str): The message displayed when prompting for input in an interactive context.
    
    Returns:
        float | None: A valid temperature value if conversion succeeds; otherwise returns None.
                     In this specific non-interactive run, the sample block will pass pre-defined strings 
                     to bypass actual user interaction requirements while demonstrating error handling logic.
    """
    # Placeholder for potential future interactive use or alternative input sources (e.g., stdin)
    try:
        value_str = "25"  # Simulating a successful numeric string in the sample block context
        return float(value_str)
    except ValueError as e:
        print(f"Error converting temperature to number: {e}")
        return None

def calculate_average(temp1_raw: str, temp2_raw: str) -> tuple[float | None, list[str]]:
    """
    Calculates the average of two temperatures with error handling for non-numeric inputs.

    This function attempts to convert the input strings to floats and computes their mean.
    It handles cases where either or both inputs are not valid numbers.

    Args:
        temp1_raw (str): String representation of the first temperature value.
        temp2_raw (str): String representation of the second temperature value.
    
    Returns:
        tuple[float | None, list[str]]: A tuple containing:
            - The calculated average as a float if both inputs are valid; otherwise None.
            - A list of error messages encountered during processing for logging purposes.
    """
    errors = []

    # Attempt to convert first temperature
    try:
        temp1 = float(temp1_raw)
    except ValueError:
        return None, [f"Invalid input for Temperature 1: '{temp1_raw}'"]

    # Attempt to convert second temperature
    try:
        temp2 = float(temp2_raw)
    except ValueError:
        return None, [f"Invalid input for Temperature 2: '{temp2_raw}'"]

    average = (temp1 + temp2) / 2
    
    if not isinstance(average, (int, float)):
        errors.append("Calculated result is unexpectedly non-numeric.")
    
    return average, []

if __name__ == '__main__':
    # Hard-coded sample values as per requirements to avoid user input or command-line arguments.
    SAMPLE_TEMP_1 = "30"      # Valid numeric string simulating a temperature in Celsius/Fahrenheit
    SAMPLE_TEMP_2 = "-5"      # Another valid numeric value
    
    print("Processing hard-coded sample temperatures...")

    # Calculate average using the robust function with pre-defined strings.
    result, error_messages = calculate_average(SAMPLE_TEMP_1, SAMPLE_TEMP_2)

    if result is not None:
        print(f"The average of {SAMPLE_TEMP_1} and {SAMPLE_TEMP_2} is {result}.")
    else:
        # In a truly interactive scenario with non-numeric input like "abc", this block would show errors.
        # Here, since inputs are valid strings representing numbers, no error messages will be generated by the logic above 
        # unless we intentionally test invalid cases in future iterations of this module's testing suite.
        print("Error: Could not calculate average due to input validation failure.")

    # Demonstration of error handling with an explicit non-numeric case for robustness verification.
    INVALID_INPUT = "invalid_number"
    
    result_invalid, errors_invalid = calculate_average(SAMPLE_TEMP_1, INVALID_INPUT)
    
    if result_invalid is None:
        print(f"\nHandled invalid input '{INVALID_INPUT}' gracefully.")
        for error in errors_invalid:
            print(error)