def generate_substrings(s: str):
    """
    Generator function that yields all possible substrings of a given string s.
    
    Substrings are generated by iterating through every possible start index i 
    and end index j (inclusive) where 0 <= i <= j < len(s).
    
    Args:
        s (str): The input string to generate substrings from.
        
    Yields:
        str: Each substring starting at index i and ending at index j-1.
    """
    length = len(s)
    for start in range(length):
        for end in range(start + 1, length + 1):
            yield s[start:end]

if __name__ == '__main__':
    # Hard-coded sample values to demonstrate functionality without user input
    test_strings = [
        "abc",
        "",
        "a"
    ]

    for test_str in test_strings:
        print(f"\nSubstrings of '{test_str}':")
        count = 0
        for substring in generate_substrings(test_str):
            print(substring)
            count += 1
        print(f"Total substrings generated: {count}")