def split_by_delimiters(phrase: str, delimiters: str) -> list[str]:
    """
    Splits a phrase into contiguous segments based on specified delimiter characters.
    
    Args:
        phrase (str): The input string to be split.
        delimiters (str): A string containing all unique delimiter characters.
        
    Returns:
        list[str]: A list of non-empty substrings resulting from the split operation.
                   Consecutive empty strings are not included in the result unless 
                   explicitly generated by non-consecutive splits, but typically 
                   adjacent separators result in skipped segments to avoid empty entries.
    
    Example usage (non-interactive):
        phrase = "a,b;c"
        delimiters = ",;?"
        # Result: ['a', 'b', 'c']
        
        phrase = "a::b"
        delimiters = ":" 
        # Result: ['a', '', 'b'] -> However, based on common expectation of contiguous segments,
        # we will filter out consecutive empty strings to return meaningful segments.
    """
    
    if not isinstance(phrase, str) or not isinstance(delimiters, str):
        raise TypeError("Both phrase and delimiters must be strings.")

    result = []
    start_index = 0
    
    for delimiter in set(delimiters):  # Use unique delimiters to avoid complex logic with sets vs lists
        current_start = -1
        
        while True:
            if delimiter not in phrase or (phrase.count(delimiter) == 0 and len(phrase.strip()) > 0):
                break

if __name__ == '__main__':
    pass
