import sys

def generate_substrings(s: str):
    """
    Generator function that yields all possible substrings of a given string s.
    
    Substrings are generated by iterating through all valid start and end indices,
    where the end index is inclusive (to match typical slicing behavior in Python).
    
    This approach uses O(1) memory per iteration as it only stores one substring at a time,
    avoiding the creation of intermediate lists or storing all substrings simultaneously.
    
    Args:
        s (str): The input string to generate substrings from.
        
    Yields:
        str: Substrings starting and ending at different indices within the original string.
    
    Example usage:
        >>> list(generate_substrings("abc"))
        ['a', 'ab', 'abc', 'b', 'bc', 'c']
    """
    n = len(s)
    for start in range(n):
        # Optimization: slice from end to avoid creating full copies if not needed, 
        # but since we need the actual substring content, slicing is necessary.
        for end in range(start + 1, n + 1):
            yield s[start:end]

if __name__ == '__main__':
    sample_string = "hello"
    
    print(f"Generating substrings from: '{sample_string}'")
    count = 0
    
    # Using a list to capture output for the sample block demonstration 
    # as printing immediately might be overwhelming, but we could also iterate directly.
    # To ensure memory efficiency during generation, we will yield and process one by one.
    
    print("\nSubstrings generated:")
    for substring in generate_substrings(sample_string):
        count += 1
        if count <= 6:  # Print first few to avoid massive output clutter
            print(f"Index range [{len(substring)-2}:{count}], Substring: '{substring}'")
        
        # Optional demonstration of memory efficiency by not storing the list
    else:
        total_count = count
        
        if total_count > 6 and sample_string == "hello":
            print(f"\n... Total substrings generated for this string: {total_count}")

# Additional test case with a shorter string to verify functionality explicitly in logic flow
test_case_1 = generate_substrings("ab")
results_a = []
for sub in test_case_1:
    results_a.append(sub)
    
print(f"\nTest Case 2 - Input 'ab': {results_a}")

# Ensure no interactive calls or external dependencies are triggered