import math

def convex_hull_monotone_chain(points):
    """
    Computes the vertices of the smallest enclosing convex polygon (Convex Hull) 
    using the Monotone Chain algorithm. Returns a list of points in counter-clockwise order.
    
    Args:
        points: List of [x, y] tuples representing 2D coordinates.
        
    Returns:
        List of vertices forming the convex hull.
    """
    if not points:
        return []

    # Sort by x-coordinate (then y) to form a sorted sequence
    pts_sorted = sorted(points, key=lambda p: (p[0], p[1]))
    
    n = len(pts_sorted)
    if n == 1:
        return [pts_sorted[0]]
    
    def cross_product(o, a, b):
        """Returns the cross product of vectors OA and AB.
        
        Values: Positive -> Left turn, Negative -> Right turn, Zero -> Collinear.
        """
        ox, oy = o
        ax, ay = a
        bx, by = b
        
        val = (ax - ox) * (by - oy) - (ay - oy) * (bx - ox)
        return val

    # Build lower hull
    lower = []
    for p in pts_sorted:
        while len(lower) >= 2 and cross_product(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)

    # Build upper hull
    upper = []
    for p in reversed(pts_sorted):
        while len(upper) >= 2 and cross_product(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)

    # Concatenate lower and upper to get the full hull. 
    # The last point of each list is redundant, so we remove it before combining.
    return lower[:-1] + upper[:-1]

def compute_area_convex_hull(points):
    """
    Computes the area of the smallest convex polygon enclosing all given points.
    
    Uses the Shoelace formula (Surveyor's formula) on the vertices 
    generated by the Monotone Chain algorithm to calculate the exact area.
    
    Args:
        points: List of [x, y] tuples representing 2D coordinates.
        
    Returns:
        The signed area as a float. For an absolute area, take the absolute value.
    """
    hull = convex_hull_monotone_chain(points)
    
    if len(hull) < 3:
        return 0.0

    n = len(hull)
    area_sum = 0.5
    
    for i in range(n):
        x1, y1 = hull[i]
        x2, y2 = hull[(i + 1) % n]
        
        # Shoelace formula term: (x_i * y_{i+1} - x_{i+1} * y_i) / 2
        area_sum += x1 * y2 - x2 * y1

    return abs(area_sum)

if __name__ == '__main__':
    # Hard-coded sample values: List of random-like integer coordinates forming a polygon with interior points.
    sample_points = [
        (0, 0),   # Origin
        (5, -2),  # Right down
        (6, -1),  # Far right down slightly up
        (4, 3),   # Top left relative to far right
        (-2, 2)   # Left top
    ]

    area = compute_area_convex_hull(sample_points)
    
    print(f"Input points: {sample_points}")
    print(f"Hull vertices count: {len(convex_hull_monotone_chain(sample_points))}")
    print(f"Area of the smallest enclosing convex polygon: {area:.2f} square units")