def generate_substrings(s: str):
    """
    Generator function that yields all possible substrings of a given string s.
    
    Substrings are generated by iterating through all valid start and end indices (inclusive).
    For each pair of indices, the substring from index i to j+1 is yielded if i <= j.

    Parameters:
        s (str): The input string for which substrings will be generated.

    Yields:
        str: Substrings extracted based on start and end indices.
    
    Memory Efficiency:
        This generator processes one substring at a time, yielding results immediately
        without storing them in memory or creating intermediate lists. It avoids 
        slicing the entire string multiple times by using index-based extraction only when needed.

    Example usage:
        >>> for sub in generate_substrings("abc"):
        ...     print(sub)
        ('', 0, 'a') -> a
        (1, 'b') -> b
        (2, c), etc.)
        
        Note: The example above is illustrative; actual output format depends on implementation.
    """
    
    n = len(s)
    
    # Iterate over all possible start indices i from 0 to n-1
    for i in range(n):
        # For each starting position, iterate end index j from i to n-1 (inclusive)
        for j in range(i, n):
            yield s[i : j + 1]

if __name__ == '__main__':
    sample_string = "abc"

    print(f"All substrings of '{sample_string}':")
    
    count = 0
    for substring in generate_substrings(sample_string):
        # Yield the actual string content, not just indices or tuples as per typical expectations.
        # However, to match common generator behavior where we might want index info if requested:
        # Here we strictly follow task: yield substrings defined by start/end logic (implicitly).
        
        print(f"Substring starting at {count}: '{substring}'")
        count += 1
        
    total_count = sum(1 for _ in generate_substrings(sample_string))
    
    print(f"\nTotal number of substrings generated: {total_count}")