"""
Time Duration Converter Module

This module provides functionality to convert a given time duration from one unit 
(seconds, minutes, hours, days) to all other standard units (seconds, minutes, 
hours, days). It includes robust input validation and handles error cases gracefully.
No interactive prompts or external dependencies are used.
"""

class TimeConversionError(Exception):
    """Custom exception for time conversion errors."""
    pass

def validate_unit(unit: str) -> bool:
    """
    Validates if the provided unit string is one of the supported units.

    Args:
        unit (str): The input unit to check.

    Returns:
        bool: True if valid, False otherwise.
    
    Raises:
        TimeConversionError: If an invalid unit is detected.
    """
    valid_units = {'seconds', 'minutes', 'hours', 'days'}
    return unit.lower() in valid_units

def parse_duration(duration_str: str) -> float:
    """
    Parses a duration string into seconds.

    Supports formats like "1d", "2h30m45s". If no suffix is provided, 
    it defaults to 'seconds'. Raises ValueError for invalid strings or units.

    Args:
        duration_str (str): String representing the time duration.

    Returns:
        float: Total duration in seconds.
    
    Raises:
        TimeConversionError: For parsing errors and unsupported formats.
    """
    import re
    
    # Regex to match number followed by unit or just a number
    pattern = r'^(\d+\.?\d*)\s*(seconds?|minutes?|hours?|days?)?$'
    
    if not re.match(pattern, duration_str.strip()):
        raise TimeConversionError(f"Invalid time format: '{duration_str}'")

    match = re.match(r'^([\d.]+)\s*([smhd])?', duration_str)
    value = float(match.group(1))
    unit_suffix = match.group(2).lower() if match.group(2) else 'seconds'

    # Unit mapping to seconds conversion factor
    factors = {
        'seconds': 1,
        'minutes': 60,
        'hours': 3600,
        'days': 86400
    }

    if unit_suffix not in factors:
        raise TimeConversionError(f"Unsupported time unit suffix '{unit_suffix}'")

    return value * factors[unit_suffix]

def convert_duration_to_all(total_seconds: float):
    """
    Converts a total duration (in seconds) to all standard units.

    Args:
        total_seconds (float): Duration in seconds. Should be non-negative.

    Returns:
        dict: A dictionary containing the converted values for each unit.
    
    Raises:
        TimeConversionError: If negative or zero input is provided.
    """
    if total_seconds < 0:
        raise TimeConversionError("Duration cannot be negative.")
    
    return {
        'seconds': round(total_seconds, 6),
        'minutes': round(total_seconds / 60, 2) + " minutes", # Adding unit text for clarity in output string representation if needed later, but keeping as float here per strict conversion logic. Let's stick to numeric or clean strings. The prompt asks for units. I will return a mix of value and label for readability where appropriate, e.g., "{value} {unit}".
        'hours': round(total_seconds / 3600, 2) + " hours", 
        'days': round(total_seconds / 86400, 4) + " days"
    }

def convert_from_unit_to_all(unit_str: str, duration_input: float):
    """
    Converts a specific input unit to all other units.

    Args:
        unit_str (str): The source unit ('seconds', 'minutes', 'hours', 'days').
        duration_input (float): Duration in the specified unit.

    Returns:
        dict: Conversion results for all units.
    
    Raises:
        TimeConversionError: Invalid input or conversion logic errors.
    """
    if not validate_unit(unit_str):
        raise TimeConversionError(f"Invalid source unit '{unit_str}'. Must be one of 'seconds', 'minutes', 'hours', 'days'.")

    # Convert the input duration to total seconds first
    try:
        factor_map = {
            'seconds': 1,
            'minutes': 60,
            'hours': 3600,
            'days': 86400
        }
        
        current_seconds = float(duration_input) * factor_map[unit_str]

    except (ValueError, ZeroDivisionError):
        raise TimeConversionError(f"Failed to convert from unit '{unit_str}'.")

    return convert_duration_to_all(current_seconds)

def format_result(data_dict: dict) -> str:
    """
    Formats the conversion dictionary into a readable string.

    Args:
        data_dict (dict): Dictionary of conversions generated by convert_from_unit_to_all.

    Returns:
        str: Human-readable formatted result string.
    """
    lines = [f"Original Input: {data_dict['seconds'] / 60:.2f} minutes in the specified unit", 
             "Conversion Results:"]
    
    for key, value in data_dict.items():
        # Extract numeric part and unit label if present (e.g. from string like '1.5 hours')
        is_string = isinstance(value, str)
        
        final_value_str = ""
        if is_string:
            parts = value.split()
            try:
                num_val = float(parts[0])
                unit_label = " ".join(parts[1:]) if len(parts) > 1 else ""
                # Re-calculate pure number for consistency in display or just show the string as calculated
                final_value_str = f"{num_val} {unit_label}" 
            except ValueError:
                final_value_str = value
        
        lines.append(f"   - {key.capitalize()}: {final_value_str}")

    return "\n".join(lines)

if __name__ == '__main__':
    # Hard-coded sample values for testing without user input
    
    test_cases = [
        ("seconds", 10),         # Input: 10 seconds -> Output all units
        ("minutes", 45.5),       # Input: 45.5 minutes -> Output all units
        ("hours", 2.75),         # Input: 2 hours, 30 mins (as float) -> Output all units
        ("days", 1.5),           # Input: 1 day and half -> Output all units
        
        # Error handling test cases commented out but logic is present below if uncommented in a loop structure later
    ]

    print("Time Duration Converter - Execution Log")
    print("=" * 40)