version: '3.12'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  generator:
    build: .
    container_name: dataset_generator
    environment:
      - OLLAMA_URL=http://ollama:11434 
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama 

volumes:
  ollama_data: